---
title: "Ejemplos variables aleatorias continuas"
author: "Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir"
date: ''
output:
  beamer_presentation: 
    theme: Warsaw
    includes: 
      in_header: "preamble.tex"
  slidy_presentation:
    incremental: no
  ioslides_presentation:
    incremental: no
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Coste de la climatización de una piscina (64 205)

Un hotel de alta montaña con pistas de esquí dispone de una piscina  climatizada se estima que en el mes más frío  el coste de $Y$ de la factura energética en euros depende de otra variable aleatoria $T$ que es la temperatura media del mes en grados centígrados según la siguiente relación lineal $Y=1000-6\cdot T$.

Supongamos que la temperatura de ese ese mes sigue una distribución  con media $\mu_T=E(T)=-5$ grados y varianza $\sigma_X^2=Var(X)=4.$

* Calcular la media del coste.
* Calcular la desviación típica del coste.


## Coste de la climatización de una piscina 

Solución



## Transformación de una v.a. $X\equiv N(\mu,\sigma)$ en una normal estándar 

Recordemos que si $X\equiv N(\mu,\sigma)$ entonces $Z=\frac{X-\mu}{\sigma}\equiv N(0,1).$

$$F_X(x)=P(X\leq x)=P\left(\frac{X-\mu}{\sigma}\leq \frac{z-\mu}{\sigma}\right)=P\left(Z\leq \frac{z-\mu}{\sigma}\right).$$







## Cartera de valores 


Supongamos que disponemos de cartera  de reanta variable que tiene un valor medio de 500000 euros una desviación estándar de 15000  

Si $X$ es el valor de la cartera y asumimos que tiene distribución aproximadamente normal ¿cuál es la probabilidad de que el valor de la cartera se encuentre entre 485000 y 520000 euros.

